name: Crosswordstreak
options:
  bundleIdPrefix: com.shimondeitel.crosswordlog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Crosswordstreak:
    type: application
    platform: iOS
    sources:
      - path: Crosswordstreak
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.crosswordlog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Crosswordstreak/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  CrosswordstreakTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CrosswordstreakTests
      - path: Crosswordstreak.storekit
    dependencies:
      - target: Crosswordstreak
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.crosswordlog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  CrosswordstreakUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: CrosswordstreakUITests
    dependencies:
      - target: Crosswordstreak
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.crosswordlog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Crosswordstreak:
    build:
      targets:
        Crosswordstreak: all
        CrosswordstreakTests: [test]
        CrosswordstreakUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Crosswordstreak.storekit
    test:
      config: Debug
      storeKitConfiguration: Crosswordstreak.storekit
      targets:
        - CrosswordstreakTests
        - CrosswordstreakUITests
    archive:
      config: Release
